import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  SafeAreaView,
  ScrollView,
  TouchableOpacity,
  Alert,
  ActivityIndicator,
  Share,
} from 'react-native';
import { COLORS, SPACING, TYPOGRAPHY, RADIUS } from '../theme';
import { GovHeader, GovButton } from '../components/gov';
import Icon from '../components/Icon';

export default function ReportDetailScreen({ navigation, route }) {
  const { reportId, reportType } = route.params;
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [downloading, setDownloading] = useState(false);

  useEffect(() => {
    loadReport();
  }, []);

  const loadReport = async () => {
    try {
      if (reportType === 'water') {
        const { getWaterTestById } = require('../database/operations');
        const test = await getWaterTestById(reportId);
        setReport(test);
      } else if (reportType === 'survey') {
        const AsyncStorage = require('@react-native-async-storage/async-storage').default;
        const surveysData = await AsyncStorage.getItem('pending_household_surveys');
        const surveys = JSON.parse(surveysData || '[]');
        const found = surveys.find(s => s.id === reportId);
        setReport(found);
      } else {
        // Other report types not yet implemented
        setReport(null);
      }
    } catch (error) {
      console.error('Error loading report:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleDelete = async () => {
    Alert.alert(
      'Delete Report',
      'Are you sure you want to delete this report? This action cannot be undone.\n\nक्या आप इस रिपोर्ट को हटाना चाहते हैं? यह क्रिया पूर्ववत नहीं की जा सकती।',
      [
        { text: 'Cancel • रद्द करें', style: 'cancel' },
        {
          text: 'Delete • हटाएं',
          style: 'destructive',
          onPress: async () => {
            try {
              if (reportType === 'water') {
                const { deleteWaterTest } = require('../database/operations');
                await deleteWaterTest(reportId);
                
                Alert.alert(
                  'Deleted',
                  `Report deleted successfully.\n\nरिपोर्ट सफलतापूर्वक हटा दी गई।`,
                  [{ text: 'OK', onPress: () => navigation.goBack() }]
                );
              } else if (reportType === 'survey') {
                const AsyncStorage = require('@react-native-async-storage/async-storage').default;
                const surveysData = await AsyncStorage.getItem('pending_household_surveys');
                const surveys = JSON.parse(surveysData || '[]');
                const updated = surveys.filter(s => s.id !== reportId);
                await AsyncStorage.setItem('pending_household_surveys', JSON.stringify(updated));
                
                Alert.alert(
                  'Deleted',
                  `Survey deleted successfully.\n\nसर्वेक्षण सफलतापूर्वक हटा दी गई।`,
                  [{ text: 'OK', onPress: () => navigation.goBack() }]
                );
              } else {
                Alert.alert('Info', 'Delete functionality for this report type is not yet implemented');
              }
            } catch (error) {
              console.error('Delete error:', error);
              Alert.alert('Error', 'Failed to delete report');
            }
          },
        },
      ]
    );
  };

  const downloadPDF = async () => {
    setDownloading(true);
    try {
      // Simulate PDF generation
      await new Promise(resolve => setTimeout(resolve, 1500));
      Alert.alert('Success', 'Report exported as PDF successfully!');
    } catch (error) {
      Alert.alert('Error', 'Failed to generate PDF');
    } finally {
      setDownloading(false);
    }
  };

  const handleShare = async () => {
    try {
      let shareMessage = `ArogyaJal Report\n\n`;
      
      if (reportType === 'survey') {
        shareMessage += `Household Survey Report\n`;
        shareMessage += `Head of Household: ${report.headOfHousehold || 'N/A'}\n`;
        shareMessage += `Village: ${report.village || 'N/A'}\n`;
        shareMessage += `Total Members: ${report.totalMembers || 'N/A'}\n`;
        shareMessage += `Water Source: ${report.waterSource || 'N/A'}\n`;
      } else if (reportType === 'water') {
        shareMessage += `Water Test Report\n`;
        shareMessage += `Source: ${report.sourceType || 'N/A'}\n`;
        shareMessage += `pH: ${report.pH || 'N/A'}\n`;
        shareMessage += `TDS: ${report.tds ? `${report.tds} mg/L` : 'N/A'}\n`;
        shareMessage += `Risk Level: ${report.riskLevel || 'Low'}\n`;
      }
      
      shareMessage += `\nReport ID: ${report.id}\n`;
      shareMessage += `Date: ${formatDate(report.createdAt)}\n`;
      shareMessage += `\nGenerated by ArogyaJal - Government of India`;

      await Share.share({
        message: shareMessage,
        title: 'ArogyaJal Report',
      });
    } catch (error) {
      console.error('Share error:', error);
    }
  };

  const formatDate = (timestamp) => {
    if (!timestamp) return 'N/A';
    const date = new Date(timestamp);
    return date.toLocaleString('en-IN', {
      day: 'numeric',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  const getSeverityColor = (severity) => {
    if (severity === 'High') return COLORS.danger;
    if (severity === 'Medium') return COLORS.warning;
    return COLORS.success;
  };

  if (loading) {
    return (
      <SafeAreaView style={styles.container}>
        <GovHeader
          title="Report Details"
          subtitle="रिपोर्ट विवरण"
          showBack
          onBackPress={() => navigation.goBack()}
        />
        <View style={styles.loadingContainer}>
          <ActivityIndicator size="large" color={COLORS.primary} />
        </View>
      </SafeAreaView>
    );
  }

  if (!report) {
    return (
      <SafeAreaView style={styles.container}>
        <GovHeader
          title="Report Details"
          subtitle="रिपोर्ट विवरण"
          showBack
          onBackPress={() => navigation.goBack()}
        />
        <View style={styles.errorContainer}>
          <Text style={styles.errorIcon}>⚠️</Text>
          <Text style={styles.errorText}>Report not found</Text>
          <TouchableOpacity style={styles.backButton} onPress={() => navigation.goBack()}>
            <Text style={styles.backButtonText}>Go Back</Text>
          </TouchableOpacity>
        </View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.container}>
      <GovHeader
        title="Report Details"
        subtitle="रिपोर्ट विवरण"
        showBack
        onBackPress={() => navigation.goBack()}
        rightComponent={
          <TouchableOpacity onPress={downloadPDF} disabled={downloading}>
            {downloading ? (
              <ActivityIndicator size="small" color={COLORS.primary} />
            ) : (
              <Icon name="download" size={24} color={COLORS.primary} />
            )}
          </TouchableOpacity>
        }
      />

      <ScrollView style={styles.content}>
        {/* Report Information */}
        {reportType === 'survey' && (
          <>
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>Patient Information</Text>
              <View style={styles.card}>
                <View style={styles.infoRow}>
                  <Text style={styles.infoLabel}>Name:</Text>
                  <Text style={styles.infoValue}>{report.headOfHousehold || 'N/A'}</Text>
                </View>
                <View style={styles.infoRow}>
                  <Text style={styles.infoLabel}>Village:</Text>
                  <Text style={styles.infoValue}>{report.village || 'N/A'}</Text>
                </View>
                <View style={styles.infoRow}>
                  <Text style={styles.infoLabel}>Total Members:</Text>
                  <Text style={styles.infoValue}>{report.totalMembers || 'N/A'}</Text>
                </View>
                <View style={styles.infoRow}>
                  <Text style={styles.infoLabel}>Contact:</Text>
                  <Text style={styles.infoValue}>{report.contactNumber || 'N/A'}</Text>
                </View>
              </View>
            </View>

            <View style={styles.section}>
              <Text style={styles.sectionTitle}>Water Source & Safety</Text>
              <View style={styles.card}>
                <View style={styles.infoRow}>
                  <Text style={styles.infoLabel}>Water Source:</Text>
                  <Text style={styles.infoValue}>{report.waterSource || 'N/A'}</Text>
                </View>
                <View style={styles.infoRow}>
                  <Text style={styles.infoLabel}>Treatment:</Text>
                  <Text style={styles.infoValue}>
                    {Array.isArray(report.waterTreatment) 
                      ? report.waterTreatment.join(', ') 
                      : report.waterTreatment || 'None'}
                  </Text>
                </View>
              </View>
            </View>
          </>
        )}

        {reportType === 'water' && (
          <>
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>Water Test Details</Text>
              <View style={styles.card}>
                <View style={styles.infoRow}>
                  <Text style={styles.infoLabel}>Source Type:</Text>
                  <Text style={styles.infoValue}>{report.sourceType || 'N/A'}</Text>
                </View>
                <View style={styles.infoRow}>
                  <Text style={styles.infoLabel}>Source Name:</Text>
                  <Text style={styles.infoValue}>{report.sourceName || 'N/A'}</Text>
                </View>
                <View style={styles.infoRow}>
                  <Text style={styles.infoLabel}>pH Level:</Text>
                  <Text style={styles.infoValue}>{report.pH || 'N/A'}</Text>
                </View>
                <View style={styles.infoRow}>
                  <Text style={styles.infoLabel}>TDS:</Text>
                  <Text style={styles.infoValue}>{report.tds ? `${report.tds} mg/L` : 'N/A'}</Text>
                </View>
                <View style={styles.infoRow}>
                  <Text style={styles.infoLabel}>Risk Level:</Text>
                  <View style={[styles.riskBadge, { backgroundColor: getSeverityColor(report.riskLevel) + '20' }]}>
                    <Text style={[styles.riskText, { color: getSeverityColor(report.riskLevel) }]}>
                      {report.riskLevel || 'Low'}
                    </Text>
                  </View>
                </View>
              </View>
            </View>
          </>
        )}

        {/* Additional Information */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Additional Information</Text>
          <View style={styles.card}>
            {report.notes && (
              <View style={styles.infoRow}>
                <Text style={styles.infoLabel}>Notes:</Text>
                <Text style={styles.infoValue}>{report.notes}</Text>
              </View>
            )}
            <View style={styles.infoRow}>
              <Text style={styles.infoLabel}>Status:</Text>
              <View style={[styles.statusBadge, report.synced ? styles.statusSynced : styles.statusPending]}>
                <Text style={styles.statusText}>{report.synced ? 'Synced' : 'Pending'}</Text>
              </View>
            </View>
            <View style={styles.infoRow}>
              <Text style={styles.infoLabel}>Report ID:</Text>
              <Text style={styles.infoValue}>{report.id}</Text>
            </View>
            <View style={styles.infoRow}>
              <Text style={styles.infoLabel}>Created:</Text>
              <Text style={styles.infoValue}>{formatDate(report.createdAt)}</Text>
            </View>
          </View>
        </View>

        {/* Actions */}
        <View style={styles.actions}>
          <View style={styles.actionRow}>
            <GovButton
              title="📥 PDF"
              onPress={downloadPDF}
              variant="primary"
              style={styles.halfButton}
              disabled={downloading}
              loading={downloading}
            />
            <GovButton
              title="📤 Share"
              onPress={handleShare}
              variant="secondary"
              style={styles.halfButton}
            />
          </View>
          {!report.synced && (
            <GovButton
              title="🗑️ Delete Report • रिपोर्ट हटाएं"
              onPress={handleDelete}
              variant="danger"
              fullWidth
            />
          )}
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: SPACING.xl,
  },
  errorIcon: {
    fontSize: 64,
    marginBottom: SPACING.md,
  },
  errorText: {
    fontSize: TYPOGRAPHY.fontSize.lg,
    color: COLORS.textDark,
    marginBottom: SPACING.lg,
  },
  backButton: {
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.button,
  },
  backButtonText: {
    color: COLORS.white,
    fontSize: TYPOGRAPHY.fontSize.base,
    fontWeight: TYPOGRAPHY.fontWeight.semibold,
  },
  content: {
    flex: 1,
    padding: SPACING.md,
  },
  section: {
    marginBottom: SPACING.lg,
  },
  sectionTitle: {
    fontSize: TYPOGRAPHY.fontSize.lg,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
    color: COLORS.textDark,
    marginBottom: SPACING.md,
  },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.card,
    padding: SPACING.md,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderLight,
  },
  infoLabel: {
    fontSize: TYPOGRAPHY.fontSize.sm,
    fontWeight: TYPOGRAPHY.fontWeight.semibold,
    color: COLORS.textMedium,
    width: 140,
  },
  infoValue: {
    fontSize: TYPOGRAPHY.fontSize.sm,
    color: COLORS.textDark,
    flex: 1,
  },
  riskBadge: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs,
    borderRadius: RADIUS.sm,
  },
  riskText: {
    fontSize: TYPOGRAPHY.fontSize.sm,
    fontWeight: TYPOGRAPHY.fontWeight.semibold,
  },
  statusBadge: {
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs,
    borderRadius: RADIUS.sm,
  },
  statusPending: {
    backgroundColor: COLORS.warningLight,
  },
  statusSynced: {
    backgroundColor: COLORS.successLight,
  },
  statusText: {
    fontSize: TYPOGRAPHY.fontSize.sm,
    fontWeight: TYPOGRAPHY.fontWeight.semibold,
  },
  actions: {
    gap: SPACING.md,
    marginBottom: SPACING.xl,
  },
  actionRow: {
    flexDirection: 'row',
    gap: SPACING.md,
  },
  halfButton: {
    flex: 1,
  },
});
