/**
 * Water Test Detail Screen
 * Comprehensive view of water test results
 */

import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  SafeAreaView,
  ScrollView,
  TouchableOpacity,
  Alert,
  ActivityIndicator,
  Share,
} from 'react-native';
import { COLORS, SPACING, TYPOGRAPHY, RADIUS } from '../theme';
import { GovHeader, GovCard } from '../components/gov';
import Icon from '../components/Icon';

export default function WaterTestDetailScreen({ navigation, route }) {
  const { testId } = route.params;
  const [test, setTest] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadTest();
  }, []);

  const loadTest = async () => {
    try {
      const { getWaterTestById } = require('../database/operations');
      const testData = await getWaterTestById(testId);
      setTest(testData);
    } catch (error) {
      console.error('Error loading test:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleShare = async () => {
    if (!test) return;

    const message = `
🌊 Water Test Report

📍 Source: ${test.sourceType} - ${test.sourceName || 'N/A'}
📅 Date: ${new Date(test.createdAt).toLocaleDateString()}

🧪 Test Results:
• pH Level: ${test.pH}
• FRC: ${test.frc}
• Turbidity: ${test.turbidity}
• TDS: ${test.tds || 'N/A'} mg/L
• Hardness: ${test.hardness || 'N/A'}

⚠️ Risk Level: ${test.riskLevel}

Generated by ArogyaJal - Water Health Initiative
    `.trim();

    try {
      await Share.share({ message });
    } catch (error) {
      console.error('Share error:', error);
    }
  };

  const handleDelete = () => {
    Alert.alert(
      'Delete Test',
      'Are you sure you want to delete this water test?',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Delete',
          style: 'destructive',
          onPress: async () => {
            try {
              const { deleteWaterTest } = require('../database/operations');
              await deleteWaterTest(testId);
              Alert.alert('Deleted', 'Water test deleted successfully', [
                { text: 'OK', onPress: () => navigation.goBack() }
              ]);
            } catch (error) {
              Alert.alert('Error', 'Failed to delete test');
            }
          },
        },
      ]
    );
  };

  const getRiskColor = (level) => {
    switch (level?.toLowerCase()) {
      case 'high': return COLORS.danger;
      case 'medium': return COLORS.warning;
      case 'low': return COLORS.success;
      default: return COLORS.textMedium;
    }
  };

  const getRiskIcon = (level) => {
    switch (level?.toLowerCase()) {
      case 'high': return '🔴';
      case 'medium': return '🟡';
      case 'low': return '🟢';
      default: return '⚪';
    }
  };

  if (loading) {
    return (
      <SafeAreaView style={styles.container}>
        <GovHeader
          title="Water Test Details"
          subtitle="जल परीक्षण विवरण"
          showBack
          onBackPress={() => navigation.goBack()}
        />
        <View style={styles.loadingContainer}>
          <ActivityIndicator size="large" color={COLORS.primary} />
          <Text style={styles.loadingText}>Loading test details...</Text>
        </View>
      </SafeAreaView>
    );
  }

  if (!test) {
    return (
      <SafeAreaView style={styles.container}>
        <GovHeader
          title="Water Test Details"
          subtitle="जल परीक्षण विवरण"
          showBack
          onBackPress={() => navigation.goBack()}
        />
        <View style={styles.emptyContainer}>
          <Text style={styles.emptyIcon}>❌</Text>
          <Text style={styles.emptyTitle}>Test Not Found</Text>
          <Text style={styles.emptySubtitle}>परीक्षण नहीं मिला</Text>
        </View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.container}>
      <GovHeader
        title="Water Test Details"
        subtitle="जल परीक्षण विवरण"
        showBack
        onBackPress={() => navigation.goBack()}
      >
        <TouchableOpacity onPress={handleShare} style={styles.headerButton}>
          <Icon name="share" size={24} color={COLORS.primary} />
        </TouchableOpacity>
      </GovHeader>

      <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
        {/* Risk Level Banner */}
        <View style={[styles.riskBanner, { backgroundColor: getRiskColor(test.riskLevel) + '20', borderColor: getRiskColor(test.riskLevel) }]}>
          <Text style={[styles.riskText, { color: getRiskColor(test.riskLevel) }]}>
            {getRiskIcon(test.riskLevel)} {test.riskLevel} Risk Level
          </Text>
          <Text style={styles.riskSubtext}>
            {test.riskLevel === 'High' && 'Immediate action required'}
            {test.riskLevel === 'Medium' && 'Monitor closely'}
            {test.riskLevel === 'Low' && 'Safe for consumption'}
          </Text>
        </View>

        {/* Sync Status */}
        <View style={[styles.statusBadge, test.synced === 1 ? styles.statusSynced : styles.statusPending]}>
          <Icon name={test.synced === 1 ? 'checkCircle' : 'clock'} size={16} color={COLORS.white} />
          <Text style={styles.statusText}>
            {test.synced === 1 ? 'Synced to Server' : 'Pending Sync'}
          </Text>
        </View>

        {/* Water Source Information */}
        <GovCard>
          <View style={styles.sectionHeader}>
            <Icon name="waterDrop" size={24} color={COLORS.primary} />
            <Text style={styles.sectionTitle}>Water Source • जल स्रोत</Text>
          </View>
          <View style={styles.infoRow}>
            <Text style={styles.infoLabel}>Source Type:</Text>
            <Text style={styles.infoValue}>{test.sourceType}</Text>
          </View>
          {test.sourceName && (
            <View style={styles.infoRow}>
              <Text style={styles.infoLabel}>Source Name:</Text>
              <Text style={styles.infoValue}>{test.sourceName}</Text>
            </View>
          )}
          <View style={styles.infoRow}>
            <Text style={styles.infoLabel}>Test Date:</Text>
            <Text style={styles.infoValue}>
              {new Date(test.createdAt).toLocaleDateString('en-IN', {
                day: 'numeric',
                month: 'long',
                year: 'numeric',
                hour: '2-digit',
                minute: '2-digit'
              })}
            </Text>
          </View>
          <View style={styles.infoRow}>
            <Text style={styles.infoLabel}>Test ID:</Text>
            <Text style={[styles.infoValue, styles.testId]}>{test.id}</Text>
          </View>
        </GovCard>

        {/* FTK Parameters */}
        <GovCard>
          <View style={styles.sectionHeader}>
            <Icon name="flask" size={24} color={COLORS.secondary} />
            <Text style={styles.sectionTitle}>FTK Parameters • FTK पैरामीटर</Text>
          </View>
          
          <View style={styles.parameterGrid}>
            <View style={styles.parameterCard}>
              <Text style={styles.parameterLabel}>pH Level</Text>
              <Text style={styles.parameterValue}>{test.pH}</Text>
            </View>
            <View style={styles.parameterCard}>
              <Text style={styles.parameterLabel}>FRC</Text>
              <Text style={styles.parameterValue}>{test.frc}</Text>
            </View>
            <View style={styles.parameterCard}>
              <Text style={styles.parameterLabel}>Turbidity</Text>
              <Text style={styles.parameterValue}>{test.turbidity}</Text>
            </View>
            {test.tds && (
              <View style={styles.parameterCard}>
                <Text style={styles.parameterLabel}>TDS (mg/L)</Text>
                <Text style={styles.parameterValue}>{test.tds}</Text>
              </View>
            )}
            {test.hardness && (
              <View style={styles.parameterCard}>
                <Text style={styles.parameterLabel}>Hardness</Text>
                <Text style={styles.parameterValue}>{test.hardness}</Text>
              </View>
            )}
            {test.geogenicParameter && (
              <View style={styles.parameterCard}>
                <Text style={styles.parameterLabel}>Geogenic</Text>
                <Text style={styles.parameterValue}>{test.geogenicParameter}</Text>
              </View>
            )}
          </View>
        </GovCard>

        {/* Visual Indicators */}
        <GovCard>
          <View style={styles.sectionHeader}>
            <Icon name="eye" size={24} color={COLORS.accent} />
            <Text style={styles.sectionTitle}>Visual Indicators • दृश्य संकेतक</Text>
          </View>
          <View style={styles.infoRow}>
            <Text style={styles.infoLabel}>Appearance:</Text>
            <Text style={styles.infoValue}>{test.appearance || 'N/A'}</Text>
          </View>
          {test.odour && (
            <View style={styles.infoRow}>
              <Text style={styles.infoLabel}>Odour:</Text>
              <Text style={styles.infoValue}>{test.odour}</Text>
            </View>
          )}
          {test.suspendedMatter && (
            <View style={styles.infoRow}>
              <Text style={styles.infoLabel}>Suspended Matter:</Text>
              <Text style={styles.infoValue}>{test.suspendedMatter}</Text>
            </View>
          )}
        </GovCard>

        {/* Environmental Factors */}
        {(test.nearbyRiskActivity?.length > 0 || test.rainfall24h) && (
          <GovCard>
            <View style={styles.sectionHeader}>
              <Icon name="alert" size={24} color={COLORS.warning} />
              <Text style={styles.sectionTitle}>Environmental Factors • पर्यावरणीय कारक</Text>
            </View>
            {test.rainfall24h && (
              <View style={styles.infoRow}>
                <Text style={styles.infoLabel}>Rainfall (24h):</Text>
                <Text style={styles.infoValue}>{test.rainfall24h === 'yes' ? 'Yes' : 'No'}</Text>
              </View>
            )}
            {test.nearbyRiskActivity?.length > 0 && (
              <View style={styles.riskActivitiesContainer}>
                <Text style={styles.infoLabel}>Nearby Risk Activities:</Text>
                <View style={styles.riskActivitiesList}>
                  {test.nearbyRiskActivity.map((activity, index) => (
                    <View key={index} style={styles.riskActivityChip}>
                      <Text style={styles.riskActivityText}>{activity}</Text>
                    </View>
                  ))}
                </View>
              </View>
            )}
          </GovCard>
        )}

        {/* Reporter Information */}
        <GovCard>
          <View style={styles.sectionHeader}>
            <Icon name="person" size={24} color={COLORS.info} />
            <Text style={styles.sectionTitle}>Reporter Information • रिपोर्टर जानकारी</Text>
          </View>
          <View style={styles.infoRow}>
            <Text style={styles.infoLabel}>Reporter ID:</Text>
            <Text style={styles.infoValue}>{test.reporterId || 'N/A'}</Text>
          </View>
          <View style={styles.infoRow}>
            <Text style={styles.infoLabel}>Reporter Type:</Text>
            <Text style={styles.infoValue}>{test.reporterType || 'ASHA'}</Text>
          </View>
        </GovCard>

        {/* Action Buttons */}
        {test.synced !== 1 && (
          <TouchableOpacity style={styles.deleteButton} onPress={handleDelete}>
            <Icon name="delete" size={20} color={COLORS.white} />
            <Text style={styles.deleteButtonText}>Delete Test • परीक्षण हटाएं</Text>
          </TouchableOpacity>
        )}

        <View style={{ height: SPACING.xl }} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  content: {
    flex: 1,
    padding: SPACING.md,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: SPACING.md,
    fontSize: TYPOGRAPHY.fontSize.base,
    color: COLORS.textMedium,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: SPACING.xl,
  },
  emptyIcon: {
    fontSize: 64,
    marginBottom: SPACING.md,
  },
  emptyTitle: {
    fontSize: TYPOGRAPHY.fontSize.xl,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
    color: COLORS.textDark,
    marginBottom: SPACING.xs,
  },
  emptySubtitle: {
    fontSize: TYPOGRAPHY.fontSize.base,
    color: COLORS.textMedium,
  },
  headerButton: {
    padding: SPACING.xs,
  },
  riskBanner: {
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: 2,
    marginBottom: SPACING.md,
    alignItems: 'center',
  },
  riskText: {
    fontSize: TYPOGRAPHY.fontSize.xl,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
    marginBottom: SPACING.xs,
  },
  riskSubtext: {
    fontSize: TYPOGRAPHY.fontSize.sm,
    color: COLORS.textMedium,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: RADIUS.full,
    marginBottom: SPACING.md,
    gap: SPACING.xs,
  },
  statusPending: {
    backgroundColor: COLORS.warning,
  },
  statusSynced: {
    backgroundColor: COLORS.success,
  },
  statusText: {
    fontSize: TYPOGRAPHY.fontSize.sm,
    fontWeight: TYPOGRAPHY.fontWeight.semibold,
    color: COLORS.white,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: SPACING.md,
    gap: SPACING.sm,
  },
  sectionTitle: {
    fontSize: TYPOGRAPHY.fontSize.lg,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
    color: COLORS.textDark,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderLight,
  },
  infoLabel: {
    fontSize: TYPOGRAPHY.fontSize.base,
    color: COLORS.textMedium,
    flex: 1,
  },
  infoValue: {
    fontSize: TYPOGRAPHY.fontSize.base,
    fontWeight: TYPOGRAPHY.fontWeight.semibold,
    color: COLORS.textDark,
    flex: 1,
    textAlign: 'right',
  },
  testId: {
    fontSize: TYPOGRAPHY.fontSize.xs,
    fontFamily: 'monospace',
  },
  parameterGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -SPACING.xs,
  },
  parameterCard: {
    width: '48%',
    backgroundColor: COLORS.background,
    borderRadius: RADIUS.md,
    padding: SPACING.md,
    margin: SPACING.xs,
    alignItems: 'center',
  },
  parameterLabel: {
    fontSize: TYPOGRAPHY.fontSize.sm,
    color: COLORS.textMedium,
    marginBottom: SPACING.xs,
  },
  parameterValue: {
    fontSize: TYPOGRAPHY.fontSize.xl,
    fontWeight: TYPOGRAPHY.fontWeight.bold,
    color: COLORS.primary,
  },
  riskActivitiesContainer: {
    paddingVertical: SPACING.sm,
  },
  riskActivitiesList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: SPACING.sm,
    gap: SPACING.sm,
  },
  riskActivityChip: {
    backgroundColor: COLORS.warning + '20',
    borderRadius: RADIUS.full,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.xs,
  },
  riskActivityText: {
    fontSize: TYPOGRAPHY.fontSize.sm,
    color: COLORS.warning,
    fontWeight: TYPOGRAPHY.fontWeight.medium,
  },
  deleteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.danger,
    borderRadius: RADIUS.button,
    padding: SPACING.md,
    marginTop: SPACING.md,
    gap: SPACING.sm,
  },
  deleteButtonText: {
    fontSize: TYPOGRAPHY.fontSize.base,
    fontWeight: TYPOGRAPHY.fontWeight.semibold,
    color: COLORS.white,
  },
});
