# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true

# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# React Native
newArchEnabled=false
hermesEnabled=false

# Build optimizations
android.enablePngCrunchInReleaseBuilds=true
